### ISSUE TITLE
conf file

### ISSUE THREAD

**Issue by BingBingBing525** [aubin-tchoi/shot-fpfh#1]
Hello, I would like to inquire about your conf file and how it is configured. I hope you can provide a sample. Currently, I am not sure how to handle this part while running the code.

**Comment by BingBingBing525** [comment]
I hope you can provide your data instance. My email is 18712570651@163.com Thank you.

**Comment by aubin-tchoi** [comment]
Hello, you can find the data I used to test the implementation on the Stanford 3D Scanning Repository: https://graphics.stanford.edu/data/3Dscanrep/
I used the bunny (http://graphics.stanford.edu/pub/3Dscanrep/bunny.tar.gz) and the dragon (http://graphics.stanford.edu/pub/3Dscanrep/dragon/dragon_recon.tar.gz) for my experiments.

**Comment by aubin-tchoi** [comment]
This conf file is only useful for the analysis of the method (knowing the correct transformation helps identifying the correct matches) as it specifies the transformations that would be obtained by computing rigid transforms between correct matches. In a practical setting if a ground truth is available you can use it by writing it in the same format as the conf file found in the bunny (only the lines starting with "bmesh" are read).
