### ISSUE TITLE
in parse_header     properties.append((line[2].decode(), ext + ply_dtypes[line[1]]))           KeyError: b'list'

### ISSUE THREAD

**Issue by tanzihong2001** [aubin-tchoi/shot-fpfh#6]
Your project is very helpful to my current work, but my ply data can't run through the code. I would like to ask if it is convenient for you to provide the ply file for testing, so that I can adjust my data according to it

**Comment by aubin-tchoi** [comment]
Hello,
Sure, here is a sample with two ply files!
[bunny_ply.zip](https://github.com/user-attachments/files/16577762/bunny_ply.zip)

Feel free to submit the complete stacktrace alongside the header of your PLY file if you want me to help debugging it.
